// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1misWFfJFSHSA0VpnBLNGIhuqf78Yi8',
    appId: '1:620401380831:web:09103f361a1f37ad48886a',
    messagingSenderId: '620401380831',
    projectId: 'flutter-notes-app-ab398',
    authDomain: 'flutter-notes-app-ab398.firebaseapp.com',
    storageBucket: 'flutter-notes-app-ab398.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByBwWexenbWii5pwpJX3ufC8dSR062Dtk',
    appId: '1:620401380831:android:3980df8dec4d733048886a',
    messagingSenderId: '620401380831',
    projectId: 'flutter-notes-app-ab398',
    storageBucket: 'flutter-notes-app-ab398.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjpjC7E-Rss6kL6-Cw4zx-UqMwN9xZbQI',
    appId: '1:620401380831:ios:53a2da9e8e89b53448886a',
    messagingSenderId: '620401380831',
    projectId: 'flutter-notes-app-ab398',
    storageBucket: 'flutter-notes-app-ab398.firebasestorage.app',
    iosBundleId: 'com.example.crudProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjpjC7E-Rss6kL6-Cw4zx-UqMwN9xZbQI',
    appId: '1:620401380831:ios:53a2da9e8e89b53448886a',
    messagingSenderId: '620401380831',
    projectId: 'flutter-notes-app-ab398',
    storageBucket: 'flutter-notes-app-ab398.firebasestorage.app',
    iosBundleId: 'com.example.crudProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw1misWFfJFSHSA0VpnBLNGIhuqf78Yi8',
    appId: '1:620401380831:web:8a9e2a09381753ff48886a',
    messagingSenderId: '620401380831',
    projectId: 'flutter-notes-app-ab398',
    authDomain: 'flutter-notes-app-ab398.firebaseapp.com',
    storageBucket: 'flutter-notes-app-ab398.firebasestorage.app',
  );
}
